# 🐻‍❄️〽️ minato: Fast, simple way to extract Bazel targets into a JSON Compilation Database
# Copyright (c) 2026 Noel <cutie@floofy.dev>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

module(
    name = "minato",
    repo_name = "dev_floofy_minato",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_rust", version = "0.73.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "violet", version = "26.07.03")
archive_override(
    module_name = "violet",
    integrity = "sha256-iH1sAlXANCIWd6RSBOFEfdkk58J0mljOADgmbA0GpVc=",
    urls = [
        # "https://artifacts.noelware.org/bazel-registry/violet/26.07.03/bazeldist.tgz",
        "https://github.com/Noelware/violet/releases/download/26.07.03/bazeldist.tgz",
    ],
)

_RUST_VERSION = "2026-08-25"

## Configure Rust toolchain
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    sha256s = {
        ("%s/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz" % _RUST_VERSION): "eb1c795ac9948ed837a542ec12abf3a0cd12af7ae5eeeded34f242aa4d8c8dcd",
        ("%s/clippy-nightly-x86_64-unknown-linux-gnu.tar.xz" % _RUST_VERSION): "6396ee6825a8a1e4a6fc0acc40addfa5087b22087be9cdd2bd26cb4fdefafcf6",
        ("%s/cargo-nightly-x86_64-unknown-linux-gnu.tar.xz" % _RUST_VERSION): "35ef31215d6b6952d095c6ff81a391d885b232a3e5ae74380bc856eddd315ac5",
        ("%s/llvm-tools-nightly-x86_64-unknown-linux-gnu.tar.xz" % _RUST_VERSION): "f4e3681e7752476546e487fad4abc9ad127cab03443ca658d9527edcab4b3d1a",
        ("%s/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz" % _RUST_VERSION): "6264111d3265a8ab7679779e409c48ccf07baa9e4c81752d4c5ebd71334fd4ca",
        ("%s/rustc-nightly-x86_64-pc-windows-msvc.tar.xz" % _RUST_VERSION): "",
        ("%s/clippy-nightly-x86_64-pc-windows-msvc.tar.xz" % _RUST_VERSION): "",
        ("%s/cargo-nightly-x86_64-pc-windows-msvc.tar.xz" % _RUST_VERSION): "",
        ("%s/llvm-tools-nightly-x86_64-pc-windows-msvc.tar.xz" % _RUST_VERSION): "",
        ("%s/rust-std-nightly-x86_64-pc-windows-msvc.tar.xz" % _RUST_VERSION): "",
        ("%s/rustc-nightly-aarch64-apple-darwin.tar.xz" % _RUST_VERSION): "",
        ("%s/clippy-nightly-aarch64-apple-darwin.tar.xz" % _RUST_VERSION): "",
        ("%s/cargo-nightly-aarch64-apple-darwin.tar.xz" % _RUST_VERSION): "",
        ("%s/llvm-tools-nightly-aarch64-apple-darwin.tar.xz" % _RUST_VERSION): "",
        ("%s/rust-std-nightly-aarch64-apple-darwin.tar.xz" % _RUST_VERSION): "",
    },
    versions = [
        # keep in-sync with `rust-toolchain.toml`
        ("nightly/%s" % _RUST_VERSION),
    ],
)

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "minato_pkgs",
    cargo_lockfile = "//:Cargo.lock",
    lockfile = "//:Cargo.bazel.lock",
    manifests = ["//:Cargo.toml"],
)
use_repo(crate, "minato_pkgs")
