# 🐻‍❄️〽️ minato: Fast, simple way to extract Bazel targets into a JSON Compilation Database
# Copyright (c) 2026 Noel <cutie@floofy.dev>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: CI
on:
    workflow_dispatch: {}
    push:
        branches:
            - 'issues/gh-**'
            - 'feat/**'
            - master
        paths-ignore:
            - '.github/**'
            - '.vscode/**'
            - 'nix/**'

            - CHANGELOG.md
            - renovate.json
            - flake.lock
            - .envrc
    pull_request:
        types: [opened, synchronize]
        branches:
            - 'issues/gh-**'
            - 'noel/**'
            - 'feat/**'
            - master
        paths:
            - '**'
permissions:
    contents: read
    checks: write
concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true
jobs:
    cargo:
        name: "Rust / Cargo [${{matrix.rust-version}}: ${{matrix.runner}}]"
        runs-on: ${{matrix.runner}}
        strategy:
            matrix:
                rust-version: [stable, nightly]
                runner:
                    - ubuntu-24.04
                    - windows-2025
                    - macos-26
        steps:
            - run: git config --global core.autocrlf false
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - run: rm rust-toolchain.toml
            - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
              with:
                toolchain: ${{matrix.rust-version}}

            - uses: rui314/setup-mold@7e4f20ad28a2e8ca6fd0892ccf72e2abb706b9c3 # v1
              if: ${{matrix.runner == 'ubuntu-latest'}}

            - if: ${{matrix.runner == 'ubuntu-latest'}}
              run: echo "RUSTFLAGS=-C link-arg=-fuse-ld=mold" >> $GITHUB_ENV

            - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
            - run: cargo build
    clippy:
        name: "Rust / Clippy [${{matrix.rust-version}}]"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust-version: [stable, nightly]
        steps:
            - run: git config --global core.autocrlf false
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - run: rm rust-toolchain.toml
            - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
              with:
                toolchain: ${{matrix.rust-version}}
                components: clippy

            - uses: rui314/setup-mold@7e4f20ad28a2e8ca6fd0892ccf72e2abb706b9c3 # v1
            - run: echo "RUSTFLAGS=-C link-arg=-fuse-ld=mold" >> $GITHUB_ENV
            - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
            - uses: auguwu/clippy-action@9817d076b82df0194935be9db6154c56ac07b317 # 1.5.0
              with:
                token: ${{github.token}}
    bazel:
        name: "Bazel [${{matrix.bazel}}: ${{matrix.runner}}]"
        runs-on: ${{matrix.runner}}
        strategy:
            matrix:
                bazel: ["7.7.1", "8.6.0", "9.1.0"]
                runner:
                    - ubuntu-24.04
                    - windows-2025
                    - macos-26
        env:
            USE_BAZEL_VERSION: ${{matrix.bazel}}
            BAZELFLAGS: "--config=ci"
        steps:
            - run: git config --global core.autocrlf false
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
              with:
                bazelisk-cache: true
                repository-cache: true
                disk-cache: bazel-diskcache-${{matrix.runner}}

            - run: bazel build ${{env.BAZELFLAGS}} //...
